<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.theonlyal.arquillian</groupId>
	<artifactId>junit5-container-test</artifactId>
	<version>1.0.0-SNAPSHOT</version>

	<properties>
		<!--Plugins-->
		<version.maven-compiler-plugin>3.13.0</version.maven-compiler-plugin>
		<version.maven-dependency-plugin>3.6.1</version.maven-dependency-plugin>

		<version.jdk>17</version.jdk>

		<version.jakartaee>10.0.0</version.jakartaee>

		<version.arquillian.core>1.10.0.Final</version.arquillian.core>
		<version.arquillian.cube>2.0.0.Final</version.arquillian.cube>
		<version.arquillian.payara>3.1</version.arquillian.payara>
		<version.arquillian.ape>2.0.0-alpha.7</version.arquillian.ape>

		<version.shrinkwrap.resolver>3.2.1</version.shrinkwrap.resolver>

		<version.org.junit>5.13.4</version.org.junit>
		<version.postgresql.jdbc>42.7.7</version.postgresql.jdbc>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${version.maven-compiler-plugin}</version>
				<configuration>
					<source>${version.jdk}</source>
					<target>${version.jdk}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>${version.maven-dependency-plugin}</version>
				<executions>
					<execution>
						<id>copy</id>
						<phase>package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<artifactItems>
						<artifactItem>
							<groupId>org.postgresql</groupId>
							<artifactId>postgresql</artifactId>
							<type>jar</type>
							<overWrite>true</overWrite>
							<outputDirectory>${project.basedir}/src/test/resources/payara/driver/</outputDirectory>
						</artifactItem>
					</artifactItems>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.jboss.arquillian</groupId>
				<artifactId>arquillian-bom</artifactId>
				<version>${version.arquillian.core}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>${version.org.junit}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.arquillian.cube</groupId>
				<artifactId>arquillian-cube-bom</artifactId>
				<version>${version.arquillian.cube}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.jboss.shrinkwrap.resolver</groupId>
				<artifactId>shrinkwrap-resolver-bom</artifactId>
				<version>${version.shrinkwrap.resolver}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
			<version>${version.jakartaee}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.junit5</groupId>
			<artifactId>arquillian-junit5-container</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.arquillian.cube</groupId>
			<artifactId>arquillian-cube-docker</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>fish.payara.arquillian</groupId>
			<artifactId>arquillian-payara-server-remote</artifactId>
			<version>${version.arquillian.payara}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.protocol</groupId>
			<artifactId>arquillian-protocol-servlet</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.arquillian.ape</groupId>
			<artifactId>arquillian-ape-sql-container-dbunit</artifactId>
			<version>${version.arquillian.ape}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.shrinkwrap.resolver</groupId>
			<artifactId>shrinkwrap-resolver-impl-maven</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>${version.postgresql.jdbc}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>